# Generated by Django 3.2.8 on 2021-10-26 18:15

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=10, unique=True, verbose_name='USER_ID')),
                ('data_length', models.IntegerField(default=0, verbose_name='DATA_LENGTH')),
                ('processed_data', models.IntegerField(default=0, verbose_name='PROCESSED_DATA')),
                ('status', models.CharField(choices=[('INACTIVE', 'inactive'), ('ACTIVATED', 'activated'), ('REGISTERED', 'registered'), ('DONE', 'done')], default='INACTIVE', max_length=10, verbose_name='STATUS')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=10, unique=True, verbose_name='USER_ID')),
                ('city_id', models.CharField(max_length=20, null=True, verbose_name='CITY_ID')),
                ('temperature', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='TEMPERATURE')),
                ('humidity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='HUMIDITY')),
                ('status', models.CharField(choices=[('INACTIVE', 'inactive'), ('ACTIVATED', 'activated'), ('REGISTERED', 'registered'), ('DONE', 'done')], default='INACTIVE', max_length=10, verbose_name='STATUS')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
